export const DEFAULT_BRANDS = ['Nike', 'Adidas', 'Puma', 'Gucci', 'Louis Vuitton', 'Zara', 'H&M']

export const DEFAULT_CATEGORIES = [
  { id: 1, name: 'Shirt', icon: 'fas fa-shirt' },
  { id: 2, name: 'Tie', icon: 'fas fa-tie' },
  { id: 3, name: 'Socks', icon: 'fas fa-socks' },
  { id: 4, name: 'Caps', icon: 'fas fa-hat-cowboy' },
  { id: 5, name: 'Accessories', icon: 'fas fa-ring' },
]

export const CATEGORY_ICONS = {
  Shirt: 'fa-shirt',
  Tie: 'fa-tie',
  Socks: 'fa-socks',
  Caps: 'fa-hat-cowboy',
  Accessories: 'fa-ring',
}

export const NIGERIAN_UNIVERSITIES = [
  'University of Lagos (UNILAG)',
  'University of Ibadan (UI)',
  'Obafemi Awolowo University (OAU)',
  'University of Nigeria, Nsukka (UNN)',
  'Ahmadu Bello University (ABU)',
  'University of Benin (UNIBEN)',
  'University of Ilorin (UNILORIN)',
  'University of Port Harcourt (UNIPORT)',
  'Federal University of Technology, Akure (FUTA)',
  'Federal University of Technology, Minna (FUTMINNA)',
  'University of Abuja (UNIABUJA)',
  'Nnamdi Azikiwe University (UNIZIK)',
  'University of Jos (UNIJOS)',
  'University of Calabar (UNICAL)',
  'University of Maiduguri (UNIMAID)',
  'Bayero University, Kano (BUK)',
  'University of Uyo (UNIUYO)',
  'Federal University of Agriculture, Abeokuta (FUNAAB)',
  'Lagos State University (LASU)',
  'Covenant University',
  'Babcock University',
  'Afe Babalola University',
  "Redeemer's University",
  'American University of Nigeria (AUN)',
  'Landmark University',
  'Bowen University',
  'Federal University of Technology, Owerri (FUTO)',
  'Abubakar Tafawa Balewa University (ATBU)',
  'Ladoke Akintola University of Technology (LAUTECH)',
  'Michael Okpara University of Agriculture (MOUAU)',
  'Pan-Atlantic University',
  'Benson Idahosa University',
  'Al-Hikmah University',
  'Fountain University',
  'Joseph Ayo Babalola University',
  'Abia State University (ABSU)',
  'Adamawa State University (ADSU)',
  'Akwa Ibom State University (AKSU)',
  'Benue State University (BSU)',
  'Delta State University (DELSU)',
  'Ebonyi State University (EBSU)',
  'Ekiti State University (EKSU)',
  'Enugu State University of Science and Technology (ESUT)',
  'Gombe State University (GSU)',
  'Imo State University (IMSU)',
  'Jigawa State University (JSU)',
  'Kaduna State University (KASU)',
  'Kwara State University (KWASU)',
  'Nasarawa State University (NSUK)',
  'Osun State University (UNIOSUN)',
  'Plateau State University (PLASU)',
  'Rivers State University (RSU)',
  'Sokoto State University (SSU)',
  'Taraba State University (TASU)',
  'Yobe State University (YSU)',
  'Zamfara State University (ZAMSU)',
  'Federal University of Petroleum Resources, Effurun (FUPRE)',
  'Usmanu Danfodiyo University (UDUSOK)',
  'Nigerian Defence Academy (NDA)',
  'National Open University of Nigeria (NOUN)',
  'Yaba College of Technology (YABATECH)',
  'Auchi Polytechnic',
  'Kaduna Polytechnic',
  'Federal Polytechnic, Ilaro',
  'Federal Polytechnic, Nekede',
  'Other University/College',
]
